### ISSUE TITLE
Why JsonElementOrError?

### ISSUE THREAD

**Issue by MekBoss** [RicardoLuis0/ZJSON#1]
Is there are a reason to combine "actual data" class with "invalid data" class?

Did you know about existence of [ThrowAbortException("OH NO!!! Anyway...");](https://github.com/coelckers/gzdoom/blob/8c715d48cde11ac947a02e25fc4012868f7eba89/wadsrc/static/zscript/engine/base.zs#L589)?

**Comment by RicardoLuis0** [comment]
`ThrowAbortException` is the nuclear solution, this gives the caller of `JSON.parse` a way to handle invalid JSON more gracefully (it also allows more useful error messages, since it propagates from the location of the parse error down to the root element, gathering extra information along the way). Furthermore, `JsonError` is only ever returned in one occasion: parse failure, and JSON objects/arrays cannot contain `JsonError`, only `JsonElement`. If you're passing JSON data around, pass it as, at minimum, a  `JsonElement` (`JsonElementOrError` is for handling the outcome of `JSON.parse`).

You can see example usage in [zjson-example.pk3](.examples/zjson-example.pk3):
```
JsonElementOrError data=JSON.parse(Wads.ReadLump(lump),false);
if(data is "JsonError"){
	ThrowAbortException("Example.json: "..JsonError(data).what);
}
example_data=ExampleOptions.deserialize(JsonElement(data));
```
